#!/bin/bash

lock() {
    i3lock -i $HOME/wallpapers/lockscreen.png
}

notify-user() {
    #Detect the user using such display
    local user=$(whoami)

    notify-send -u critical -t 4000 "battery warning" "\n$user, your battery is low"
}

main(){
    acpi -b | awk -F'[,:%]' '{print $2, $3}' | {
        read -r status capacity

        if [ "$status" = Discharging ]; then
            if [ "$capacity" -lt 10 ] && [ "$capacity" -gt 5 ]; then
                notify-user & aplay -q ~/sounds/marimbach-low-bat.wav
            elif [ "$capacity" -lt 5 ]; then
                lock && systemctl hibernate
            fi
        fi
    }
}

while true; do
    main
    sleep 180
done
