#!/bin/bash

# round 1
sleep 1500 && aplay ~/.emacs.d/elisp/pomodoro/wind-chime-rest.wav && zenity --warning --text="break time"
sleep 300 && aplay ~/.emacs.d/elisp/pomodoro/sparkle-work.wav && zenity --warning --text="back to work" # a short, 5-minute break
# round 2
sleep 1500 && aplay ~/.emacs.d/elisp/pomodoro/wind-chime-rest.wav && zenity --warning --text="break time"
sleep 300 && aplay ~/.emacs.d/elisp/pomodoro/sparkle-work.wav && zenity --warning --text="back to work"
# round 3
sleep 1500 && aplay ~/.emacs.d/elisp/pomodoro/wind-chime-rest.wav && zenity --warning --text="break time"
sleep 300 && aplay ~/.emacs.d/elisp/pomodoro/sparkle-work.wav && zenity --warning --text="back to work"
# round 4
sleep 1500 && aplay ~/.emacs.d/elisp/pomodoro/wind-chime-rest.wav && zenity --warning --text="break time"
sleep 900 && aplay ~/.emacs.d/elisp/pomodoro/early-sunrise-yey.wav && zenity --warning --text="back to work" # a long, 15-minute break

# credit Waldir Leoncio
