#!/usr/bin/env bash

# take your moments
# take screnshot and give it a name directly

prompt_path(){
    img_name=$(yad \
                   --width=200 \
                   --form \
                   --field="Name" \
                   --button="Save" \
                   --center)
}

save_img(){
    # using bash sub-string to remove '|' character from yad input
    exec xclip -se c -t image/png -o > $HOME/Pictures/moments/"${img_name:0:-1}_$(date +%F-%H:%M).png"
}

main(){
    case "$1" in
        full)
            exec maim --hidecursor | xclip -se c -t image/png
            prompt_path
            save_img
            ;;
        selection)
            exec maim -s --hidecursor | xclip -se c -t image/png
            prompt_path
            save_img
            ;;
    esac
}

main ${@}
