#!/bin/bash

# Keep Debian up to date
sudo apt -y update
sudo apt -y upgrade

# install main package
sudo apt-get install -y --no-install-recommends \
     sudo gtk3.0 xfce4 firmware-iwlwifi \
     git etckeeper wget gnupg2 pinentry-gtk2 xclip tar\
     arandr emacs-gtk rxvt-unicode-256color tmux\
     stow maim feh sxiv file-roller mpv thunar \
     yad silversearcher-ag ssh \
     thunar-archive-plugin gvfs gvfs-fuse gvfs-common gvfs-backends \
     markdown ogg123 git-crypt maildir-utils

# window manager related
sudo apt-get -y install \
     i3 i3lock rofi light dunst unclutter compton redshift \
     light network-manager-gnome alasa-utils pavucontrol

# work
sudo apt-get -y install \
     python3 python3-dev python3-venv python3-pip

# font & themes
sudo apt-get -y install arc-theme

# setup
echo "Installed base app. I will setup them for you."

## firefox
cd /opt
wget https://download-installer.cdn.mozilla.net/pub/devedition/releases/69.0b15/linux-x86_64/en-US/firefox-69.0b15.tar.bz2
tar -xf firefox-69.0b14.tar.bz2
cd firefox
ln -s ~/opt/firefox/firefox /usr/local/bin/firefox-dev

## telegram
wget https://updates.tdesktop.com/tlinux/tsetup.1.8.2.tar.xz
tar -xf tsetup.1.8.2.tar.xz
ln -s /opt/Telegram/Telegram  /usr/local/bin/Telegram

## greenclip
wget https://github.com/erebe/greenclip/releases/download/3.2/greenclip
ln -s /opt/greenclip  /usr/local/bin/greenclip

## capitane
wget https://github.com/keeferrourke/capitaine-cursors/archive/master.zip
unzip capitaine-cursors-master.zip
cd capitaine-cursors-master/
mkdir -p ~/.icons/capitaine-cursors
cp -pr dist/ ~/.icons/capitaine-cursors

## i3-gaps
wget https://github.com/maestrogerardo/i3-gaps-deb/archive/master.zip
unzip i3-gaps-deb-master.zip
cd i3-gaps-deb-master
sudo chmod +x i3-gaps-deb
./i3-gaps-deb

# fonts
wget https://github.com/adobe-fonts/source-code-pro/archive/release.zip
unzip source-code-pro-release.zip
cd source-code-pro-release/
mv TTF/ source-code-pro/
mkdir -p ~/.local/share/fonts/
mv source-code-pro/ ~/.local/share/fonts/

wget https://use.fontawesome.com/releases/v5.10.1/fontawesome-free-5.10.1-desktop.zip
unzip fontawesome-free-5.10.1-desktop.zip
cd fontawesome-free-5.10.1-desktop/
mv otfs/ font-awesome/
mv font-awesome/ ~/.local/share/fonts/
fc-cache -fv

# python
pip3 install virtualenvwrapper
mkvirtualenv --python=/usr/bin/python3.7 global37
workon global37
pip install setuptools
pip install flake8 black

# setup dotfiles
cd $HOME
git clone https://github.com/azzamsa/dotfiles
cd dotfiles
for d in */ ; do
    stow "$d"
done

# touchpad
# https://unix.stackexchange.com/a/337218
sudo apt remove xserver-xorg-input-synaptics
sudo apt install xserver-xorg-input-libinput
sudo echo 'Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
EndSection' > /etc/X11/xorg.conf.d/40-libinput.conf

# wallpaper & sounds
cd $HOME
mkdir sounds wallpapers
cd ~/Pictures
mkdir moments screenshots bin code-coba-home

echo "Setup finished"
