#!/bin/bash

# Keep Debian up to date
sudo apt-get -y update

# install main package
sudo apt-get -y install \
     dkms build-essential linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,')

# utilities
sudo apt-get -y install \
     borgbackup ncdu htop mat bleachbit \
     unzip curl wget p7zip p7zip-full unar unrar-free\
     gparted-gtk

# programming
sudo apt-get -y install \
     docker.io docker-compose mycli sqlitebrowser \
     borgbackup ncdu htop mat bleachbit etckeeper


# office
sudo apt-get -y install \
     libreoffice libreoffice-style-tango libreoffice-gtk libreoffice-gtk3 \
     okular evince  cups system-config-printer

# email
sudo apt-get -y install \
     maildir-util isync w3m


# multimedia
sudo apt-get -y install \
     mpv audacity openshot \
     gimp inkscape ffmpeg

# Tor
cd ~
wget -q https://dist.torproject.org/torbrowser/9.0.1/tor-browser-linux64-9.0.1_en-US.tar.xz
tar -xf tor-browser-linux64-9.0.1_en-US.tar.xz
sudo mv firefox/ /opt/
sudo ln -s ~/opt/firefox/firefox /usr/local/bin/firefox-dev


# setup mu4e
cd ~
mkdir -p ~/Email/memail
cd ~/Email/memail
mkdir Sent Drafts Trash Archive
mu index --maildir=~/Email/memail
mbsync -c ~/Email/.mbsyncrc memail

# setup guix
sudo su
cd /tmp
wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
chmod +x guix-install.sh
wget https://sv.gnu.org/people/viewgpg.php?user_id=15145 -qO - | gpg --import -
./guix-install.sh

# setup rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo install rustfmt racer

# setup js
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash

# py3status
pip3 install islam

# pass-otp
cd /otp
sudo mkdir pass-otp
sudo chown -R $USER:$USER pass-otp/
git clone https://github.com/tadfisher/pass-otp
cd pass-otp/
sudo make install
sudo apt-get install -y oathtool

# z
cd /otp
sudo mkdir z
sudo chown -R $USER:$USER z/
git clone https://github.com/rupa/z/ z/
