#!/bin/bash

# Keep Debian up to date
sudo apt-get -y update

# install main package
sudo apt-get install -y --no-install-recommends \
     dkms build-essential linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,')

# utilities
sudo apt-get install -y --no-install-recommends \
     fish borgbackup ncdu htop mat bleachbit \
     unzip curl wget p7zip p7zip-full unar unrar-free\
     gparted-gtk torbrowser-launcher

# programming
sudo apt-get install -y --no-install-recommends \
     docker.io docker-compose mycli sqlitebrowser \
     borgbackup ncdu htop mat bleachbit etckeeper apache2-utils


# office
sudo apt-get -y install \
     libreoffice libreoffice-style-tango libreoffice-gtk libreoffice-gtk3 \
     okular okular-extra-backends evince cups system-config-printer pandoc mumble

# email
sudo apt-get -y install \
     maildir-util isync w3m


# multimedia
sudo apt-get -y install \
     mpv audacity openshot \
     gimp inkscape ffmpeg

# Tor
cd ~
wget -q https://dist.torproject.org/torbrowser/9.0.1/tor-browser-linux64-9.0.1_en-US.tar.xz
tar -xf tor-browser-linux64-9.0.1_en-US.tar.xz
sudo mv firefox/ /opt/
sudo ln -s ~/opt/firefox/firefox /usr/local/bin/firefox-dev


# setup mu4e
cd ~
mkdir -p ~/Email/memail
cd ~/Email/memail
mkdir Sent Drafts Trash Archive
mu index --maildir=~/Email/memail
mbsync -c ~/Email/.mbsyncrc memail

# setup guix
sudo su
cd /tmp
wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
chmod +x guix-install.sh
wget https://sv.gnu.org/people/viewgpg.php?user_id=15145 -qO - | gpg --import -
./guix-install.sh

# setup rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo install rustfmt racer
cargo install --git https://github.com/greshake/i3status-rust i3status-rs
cargo install cargo-edit

## rust utils
cargo install evcxr_repl
cargo install hyperfine
cargo install zoxide -f # z replacement

sudo curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o ~/.local/bin/rust-analyzer
sudo chmod +x ~/.local/bin/rust-analyzer

# setup js
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash

# py3status
pip3 install islam

# pass-otp
cd /otp
sudo mkdir pass-otp
sudo chown -R $USER:$USER pass-otp/
git clone https://github.com/tadfisher/pass-otp
cd pass-otp/
sudo make install
sudo apt-get install -y oathtool

# Go
wget -q https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.15.1.linux-amd64.tar.gz

# fish
chsh -s `which fish` # change bash to fish
vf install # virtual fish
