#!/bin/bash

# Add repository
echo "deb http://ftp.au.debian.org/debian/ bullseye main contrib non-free" | sudo tee -a /etc/apt/sources.list
echo "deb-src http://ftp.au.debian.org/debian/ bullseye main contrib non-free" | sudo tee -a /etc/apt/sources.list

# Keep Debian up to date
sudo apt -y update

# main package
# fuse required by AppImage
# libssl-dev provides certificates for culr
# libdbus-1-dev and pkg-config required by i3status-rust and other apps, such as mousepad
# audio won't work without pulseaudio
# without `gstreamer1.0-pulseaudio` apps can't play sound (such workrave can't play .wav notification sound)
sudo apt-get install -y --no-install-recommends \
     xserver-xorg xinit libdbus-1-dev pkg-config \
     sudo firmware-iwlwifi x11-xserver-utils libssl-dev \
     pavucontrol pulseaudio gstreamer1.0-pulseaudio\
     fish fuse git etckeeper gnupg2 ssh ssh-agent curl stow rsync \
     keychain


echo "exec i3" | tee -a ~/.xinitrc

# utilities
# xclip required by pass to copy to clipboard
# gvfs-fuse gvfs-backends adds support for sftp in thunar
sudo apt-get install -y --no-install-recommends \
     i3 i3lock rofi light dunst unclutter \
     pass light xclip network-manager-gnome \
     flameshot feh ristretto file-roller mousepad workrave \
     thunar thunar-archive-plugin gvfs-fuse gvfs-backends \
     htop tar zip unzip unar unrar-free ncdu mat borgbackup gparted arandr \
     mpv gimp inkscape libreoffice libreoffice-gtk3 audacity \
     okular okular-extra-backends evince system-config-printer \
     maildir-utils isync aspell aspell-en \
     zoxide ripgrep arc-theme

# work
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

sudo apt-get install -y --no-install-recommends \
     python3 python3-dev python3-venv python3-pip python3-setuptools

cargo install starship vivid fnm

# setting up `ssh-agent` in fish shell is nightmare
# I can use plain `eval (ssh-agent -c)` or `systemd --user`
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install danhper/fish-ssh-agent

# setup
echo "Installed base app. I will setup them for you."

# auto-suspend
cd /tmp
git clone --depth=1 https://github.com/azzamsa/scripts/
cd scripts
sudo mv auto-suspend/ /opt/
sudo chown -R $(whoami):$(whoami) /opt/auto-suspend
sudo ln -s /opt/auto-suspend/auto-suspend /usr/local/bin/auto-suspend

# wezterm
cd /tmp
curl -LO https://github.com/wez/wezterm/releases/download/20210814-124438-54e29167/WezTerm-20210814-124438-54e29167-Ubuntu16.04.AppImage
chmod +x WezTerm-20210814-124438-54e29167-Ubuntu16.04.AppImage
mv ./WezTerm-20210814-124438-54e29167-Ubuntu16.04.AppImage /opt/wezterm
sudo chown -R $(whoami):$(whoami) /opt/wezterm
sudo ln -s /opt/wezterm /usr/local/bin/wezterm

# aw-qt
cd /tmp
wget -q https://github.com/ActivityWatch/activitywatch/releases/download/v0.11.0/activitywatch-v0.11.0-linux-x86_64.zip
unzip activitywatch-v0.11.0-linux-x86_64.zip
mv activitywatch /opt/
sudo chown -R $(whoami):$(whoami) /opt/activitywatch
sudo ln -s /opt/activitywatch/aw-qt /usr/local/bin/aw-qt

# nextcloud
cd /tmp
wget -q https://github.com/nextcloud/desktop/releases/download/v3.3.5/Nextcloud-3.3.5-x86_64.AppImage
chmod +x Nextcloud-3.3.5-x86_64.AppImage
mv Nextcloud-3.3.5-x86_64.AppImage /opt/nextcloud
sudo chown -R $(whoami):$(whoami) /opt/nextcloud
sudo ln -s /opt/nextcloud /usr/local/bin/nextcloud

# insomnia
cd /tmp
wget -q https://github.com/Kong/insomnia/releases/download/core%402021.5.3/Insomnia.Core-2021.5.3.AppImage
chmod +x Insomnia.Core-2021.5.3.AppImage
mv Insomnia.Core-2021.5.3.AppImage /opt/insomnia
sudo chown -R $(whoami):$(whoami) /opt/insomnia
sudo ln -s /opt/insomnia /usr/local/bin/insomnia

# aspell
cd /tmp
wget -q https://ftp.gnu.org/gnu/aspell/dict/id/aspell5-id-1.2-0.tar.bz2
tar -xf aspell5-id-1.2-0.tar.bz2
cd aspell5-id-1.2-0/
./configure
make
sudo make install

## firefox
cd /tmp
wget -q https://download-installer.cdn.mozilla.net/pub/firefox/releases/92.0.1/linux-x86_64/en-US/firefox-92.0.1.tar.bz2
tar -xf firefox-92.0.1.tar.bz2
sudo mv firefox/ /opt/
sudo chown -R $(whoami):$(whoami) /opt/firefox
sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox

## telegram
cd /tmp
wget -q https://updates.tdesktop.com/tlinux/tsetup.3.1.1.tar.xz
tar -xf tsetup.3.1.1.tar.xz
sudo mv Telegram/ /opt/
sudo chown -R $(whoami):$(whoami) /opt/Telegram
sudo ln -s /opt/Telegram/Telegram /usr/local/bin/Telegram

## greenclip
cd /tmp
wget -q https://github.com/erebe/greenclip/releases/download/v4.2/greenclip
sudo mv greenclip /opt/
sudo ln -s /opt/greenclip /usr/local/bin/greenclip

## pass-otp
cd /tmp
git clone https://github.com/tadfisher/pass-otp
cd pass-otp/
sudo make install

# wallpaper, sounds, fonts, and icons
mkdir ~/sounds ~/wallpapers
cd ~/wallpapers
wget -q https://www.dropbox.com/s/o5gvczc3ymgg8vv/wallpapers.tar.gz?dl=0
tar -xf wallpapers.tar.gz
rm wallpapers.tar.gz

cd ~/sounds
wget -q https://www.dropbox.com/s/whao1ljkd26n3nw/sounds.tar.gz?dl=0
tar -xf sounds.tar.gz
rm sounds.tar.gz

# fonts
cd ~/.local/share/fonts/
wget -q https://www.dropbox.com/s/jp7s95ihd48edar/fonts.tar.gz?dl=0
tar -xf fonts.tar.gz
rm fonts.tar.gz
fc-cache -fv

# icons
mkdir ~/.icons
cd ~/.icons
wget -q https://www.dropbox.com/s/4wn1fczsx050gvl/.icons.tar.gz?dl=0
tar -xf .icons.tar.gz
rm .icons.tar.gz

# emacs
sudo apt-get build-dep emacs
inn libgccjit-9-dev
# ./configure --with-native-compilation
# make
# sudo make install


# setup dotfiles
# create directory first, otherwise stow will create top directory as symlink
# and apps will put uninteresting files under dotfiles directory
cd ~
mkdir .screenlayout
cd ~/.config/
mkdir compton dunst fish gtk-3.0 i3 i3status mpv wezterm
cd ~
git clone https://github.com/azzamsa/dotfiles
cd dotfiles
for d in */ ; do
    stow "$d"
done

# setup mu4e
# mu init --maildir=~/Email/secret --my-address=secret

# dual-monitor
# keep the laptot alive even if no HDMI connection
echo "
HandleSuspendKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchDocked=ignore
"  | sudo tee -a /etc/systemd/logind.conf

# touchpad
# https://unix.stackexchange.com/a/337218
sudo apt remove xserver-xorg-input-synaptics
sudo apt install xserver-xorg-input-libinput
sudo mkdir -p /etc/X11/xorg.conf.d/

sudo echo 'Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
EndSection' > ~/40-libinput.conf
sudo mv ~/40-libinput.conf /etc/X11/xorg.conf.d/

# fish
chsh -s `which fish` # change bash to fish
vf install # virtual fish

echo "Setup finished"
cat <<- EOF
Your next TODO:
  1. change BIOS setting for beep
  2. copy .authinfo.gpg and Email
  3. build emacs
EOF
